[project]
name = "scripts"
version = "0.1.0"
description = "small scripts to generate Rust interfaces package for various distro"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "pyyaml>=6.0.3",
    "requests>=2.32.5",
]
